### ISSUE TITLE
`--cleant` and `--rescue` leads SIGSEGV

### ISSUE THREAD

**Issue by tbrittoborges** [alevar/ORFanage#3]
Hi @alevar,
I have a specific example that causes a SIGSEGV. Here I am annotating a stringtie GTF with Ensembl CDS - I guess this is a typical workflow? To speed things up, I downsampled the query GTF, the template GTF, and the reference fasta (7MB, 24MB, 32MB). While trying to refine the CDS with `--cleant` and `--rescue`, I get a SIGSEGV error (this is independent of any other parameters):

```bash
orfanage --cleanq --cleant --non_aug --rescue --query merged_each.gtf10 --reference {fasta} --output {output} GRCh38.102.gtf
...
orfanage --cle…' terminated by signal SIGSEGV (Address boundary error)
```
My main issue is that I can't make it work even with small input files. Do you have any suggestions to work around that?

I did the coredump analysis with GDB. Where I get the error:
https://github.com/alevar/ORFanage/blob/8945c685e672d826da803236780f55de31b6022a/main.cpp#L149

<details><summary>GDB output</summary>
<p>

```
GNU gdb (GDB) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-conda-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from orfanage...
[New LWP 1315953]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by orfanage --cleanq --cleant --non_aug --rescu'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00005600978a2b14 in TX::get_codon_aa(unsigned int) ()
(gdb)  bt full
#0  0x00005600978a2b14 in TX::get_codon_aa(unsigned int) ()
No symbol table info available.
#1  0x00005600978a5fce in Transcriptome::clean_cds(bool) ()
No symbol table info available.
#2  0x00005600978cd07c in run() ()
No symbol table info available.
#3  0x00005600978714e8 in main ()
No symbol table info available.
(gdb)
```
</p>
</details>

**Comment by alevar** [comment]
This is great feedback! Template cleaning was an early feature and remained untested for some time. An easy fix, but glad it is working properly now! Thank you for reporting!
